--
-- ALTER TABLE STRUCTURE
--
ALTER TABLE STAGE_CDI.SFDC_ADVISER_HERITAGE_ARN_STG
  ADD CONSTRAINT DF_SFDC_ADVISER_HERITAGE_ARN_STG_INSERT_DATE_TIME 
  DEFAULT CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'GMT Standard Time' AS DATETIME2) FOR INSERT_DATE_TIME;

--
-- UNIQUE INDEX
--
CREATE UNIQUE INDEX SFDC_ADVISER_HERITAGE_ARN_STG_UI 
  ON STAGE_CDI.SFDC_ADVISER_HERITAGE_ARN_STG (SFDC_ADVISER_HERITAGE_ARN_ID);