--
-- ALTER TABLE STRUCTURE
--
ALTER TABLE STAGE_CDI.SFDC_ADVISER_ACCOUNT_STG
 ALTER COLUMN PRU_INVESTMENTADVICE__C    BIT;

ALTER TABLE STAGE_CDI.SFDC_ADVISER_ACCOUNT_STG
 ALTER COLUMN PRU_MORTGAGEADVICE__C    BIT;  

ALTER TABLE STAGE_CDI.SFDC_ADVISER_ACCOUNT_STG
 ALTER COLUMN PRU_INSURANCEADVICE__C    BIT;

ALTER TABLE STAGE_CDI.SFDC_ADVISER_ACCOUNT_STG
 ALTER COLUMN PRU_PENSIONXFERADVICE__C    BIT;

ALTER TABLE STAGE_CDI.SFDC_ADVISER_ACCOUNT_STG
 ALTER COLUMN PRU_DATAQUALITYISSUE_C    BIT;

ALTER TABLE STAGE_CDI.SFDC_ADVISER_ACCOUNT_STG
 ALTER COLUMN PRU_RECORDREMOVED__C    BIT;    

ALTER TABLE STAGE_CDI.SFDC_ADVISER_ACCOUNT_STG
  ADD CONSTRAINT DF_SFDC_ADVISER_ACCOUNT_STG_INSERT_DATE_TIME 
  DEFAULT CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'GMT Standard Time' AS DATETIME2) FOR INSERT_DATE_TIME;

--
-- PRIMARY KEY
--
ALTER TABLE STAGE_CDI.SFDC_ADVISER_ACCOUNT_STG 
  ADD CONSTRAINT SFDC_ADVISER_ACCOUNT_STG_PK PRIMARY KEY (PRU_PARTYROLEID__C);