--
-- ALTER TABLE STRUCTURE
--
ALTER TABLE STAGE_CDI.DPDB_REGISTERED_INDIVIDUAL_STG
 ALTER COLUMN RECORD_DELETE_IND    BIT;

ALTER TABLE STAGE_CDI.DPDB_REGISTERED_INDIVIDUAL_STG
  ADD CONSTRAINT DF_DPDB_REGISTERED_INDIVIDUAL_STG_INSERT_DATE_TIME DEFAULT CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'GMT Standard Time' AS DATETIME2) FOR INSERT_DATE_TIME;

--
-- PRIMARY KEY
--
ALTER TABLE STAGE_CDI.DPDB_REGISTERED_INDIVIDUAL_STG 
  ADD CONSTRAINT DPDB_REGISTERED_INDIVIDUAL_STG_PK PRIMARY KEY (ACCOUNT_NUMBER);