IF OBJECT_ID('STAGE_CDI.BATCH_FUNCTION') IS NULL 
  CREATE TABLE STAGE_CDI.BATCH_FUNCTION
  (
     BATCH_FUNCTION_ID       INT            NOT NULL   IDENTITY (1,1),
     FUNCTION_AREA           VARCHAR(255)   NOT NULL,
     MASTER_PIPELINE_NAME    VARCHAR(400)   NOT NULL,
     PIPELINE_NAME           VARCHAR(400)   NOT NULL,
     PIPELINE_RUN_ORDER      INT            NOT NULL
  );