IF OBJECT_ID('STAGE_CDI.BATCH_PARAMETER_HIST') IS NULL
  CREATE TABLE STAGE_CDI.BATCH_PARAMETER_HIST
  (   
    PROCESS_ID                INT            NOT NULL    IDENTITY (1,1),
    PROCESS_NAME              VARCHAR(255)   NOT NULL,
    PARAMETER_NAME            VARCHAR(255)   NOT NULL,
	PARAMETER_VALUE_DT        DATETIME2,
	PARAMETER_VALUE_NUMBER    INT,
	PARAMETER_VALUE_CHAR      VARCHAR(400),
	LASTMODIFIEDDT            DATETIME2      NOT NULL,
	LASTMODIFIEDBY            VARCHAR(255)   NOT NULL,
	ACTION_TYPE               VARCHAR(6)     NOT NULL,
	ACTIONED_BY               VARCHAR(300)   NOT NULL,
	ACTION_DATE               DATETIME2      NOT NULL
	CONSTRAINT BATCH_PARAMETER_HIST_PK PRIMARY KEY (PROCESS_NAME, PARAMETER_NAME, PROCESS_ID)
  );