IF OBJECT_ID('STAGE_CDI.SONATA_BOND_ACCOUNT_STG') IS NOT NULL 
  DROP TABLE STAGE_CDI.SONATA_BOND_ACCOUNT_STG;
  
IF OBJECT_ID('STAGE_CDI.SONATA_BOND_CLIENT_REL_STG') IS NOT NULL
  DROP TABLE STAGE_CDI.SONATA_BOND_CLIENT_REL_STG;

IF OBJECT_ID('STAGE_CDI.SONATA_BOND_CLIENT_STG') IS NOT NULL
  DROP TABLE STAGE_CDI.SONATA_BOND_CLIENT_STG;

IF OBJECT_ID('STAGE_CDI.SONATA_BOND_FRAUD_STG') IS NOT NULL
  DROP TABLE STAGE_CDI.SONATA_BOND_FRAUD_STG;

IF OBJECT_ID('STAGE_CDI.SONATA_BOND_INDI_CLIENT_STG') IS NOT NULL
  DROP TABLE STAGE_CDI.SONATA_BOND_INDI_CLIENT_STG;

IF OBJECT_ID('STAGE_CDI.SFDC_TRST_CRP_INDV_ACCOUNT_STG') IS NOT NULL
  DROP TABLE STAGE_CDI.SFDC_TRST_CRP_INDV_ACCOUNT_STG;

IF OBJECT_ID('STAGE_CDI.SFDC_ACCOUNTROLE_STG') IS NOT NULL
  DROP TABLE STAGE_CDI.SFDC_ACCOUNTROLE_STG;

IF OBJECT_ID('STAGE_CDI.SFDC_ASSET_STG') IS NOT NULL
  DROP TABLE STAGE_CDI.SFDC_ASSET_STG;

IF OBJECT_ID('STAGE_CDI.SFDC_ASSETROLE_STG') IS NOT NULL
  DROP TABLE STAGE_CDI.SFDC_ASSETROLE_STG;  