IF OBJECT_ID('STAGE_CDI.ETL_JOB_CONTROL') IS NULL
  CREATE TABLE STAGE_CDI.ETL_JOB_CONTROL
  (
     ETL_JOB_CONTROL_ID    DECIMAL(3,0),
     LAYER_NAME            VARCHAR(60),
     MAPPING_NAME          VARCHAR(60)    NOT NULL,
     PARAMETER_NAME        VARCHAR(50)    NOT NULL,
     PARAMETER_VALUE       VARCHAR(100)   NOT NULL,
     FLAG                  VARCHAR(1),
     DESCRIPTION           VARCHAR(100)
  );