IF OBJECT_ID('STAGE_CDI.DPDB_ADVISER_FIRM_STG') IS NULL 
  CREATE TABLE STAGE_CDI.DPDB_ADVISER_FIRM_STG
  (
      PARTY_ROLE_ID             VARCHAR(10)    NOT NULL,
      ORGANISATION_NAME         VARCHAR(100),
      FIRM_REFERENCE_NUMBER     VARCHAR(10)    NOT NULL,
      STATUS                    VARCHAR(50),
      REGULATORY_STATUS_ID      VARCHAR(50),
      PARTY_ROLE_TYPE_ID        VARCHAR(50),
      PERM_INVESTMENT_ADVICE    DECIMAL(1,0),
      PERM_MORTGAGE_ADVICE      DECIMAL(1,0),
      PERM_INSURANCE_ADVICE     DECIMAL(1,0),
      PERM_PENSION_ADVICE       DECIMAL(1,0),
      ADDRESS_LINE_1            VARCHAR(50),
      ADDRESS_LINE_2            VARCHAR(50),
      ADDRESS_LINE_3            VARCHAR(50),
      ADDRESS_LINE_4            VARCHAR(50),
      POSTCODE                  VARCHAR(10),
      EMAIL_URL_ADDRESS         VARCHAR(100),
      PHONE_FAX_NUMBER          VARCHAR(20),
      RECORD_UPDATE_IND         VARCHAR(32),
      RECORD_DELETE_IND         DECIMAL(1,0),
      CREATE_USER_ID            VARCHAR(255),
      INSERT_DATE_TIME          DATETIME2,
      UPDATE_DATE_TIME          DATETIME2    NOT NULL
);

IF OBJECT_ID('STAGE_CDI.DPDB_ADVISER_LEGACY_AGENCY_STG') IS NULL 
  CREATE TABLE STAGE_CDI.DPDB_ADVISER_LEGACY_AGENCY_STG
  (
      ACCOUNT_NUMBER              VARCHAR(10)    NOT NULL,
      OFFICE_PARTY_ROLE_ID        VARCHAR(10)  ,
      FIRM_PARTY_ROLE_ID          VARCHAR(10),
      ACCOUNT_STATUS              VARCHAR(1),
      OFFICE_STATUS               VARCHAR(1),
      PARTY_ROLE_TYPE_ID          VARCHAR(10),
      INDIVIDUAL_PARTY_ROLE_ID    VARCHAR(10),
      ACCOUNT_TYPE_ID             VARCHAR(20),
      LEGACY_SYSTEM_ID            VARCHAR(20),
      RECORD_UPDATE_IND           VARCHAR(32),
      RECORD_DELETE_IND           DECIMAL(1,0),
      CREATE_USER_ID              VARCHAR(255),
      INSERT_DATE_TIME            DATETIME2,
      UPDATE_DATE_TIME            DATETIME2    NOT NULL
  );

IF OBJECT_ID('STAGE_CDI.DPDB_ADVISER_NETWORK_STG') IS NULL 
  CREATE TABLE STAGE_CDI.DPDB_ADVISER_NETWORK_STG
  (
     NETWORK_PARTY_ROLE_ID     VARCHAR(10)    NOT NULL,
     REL_FIRM_PARTY_ROLE_ID    VARCHAR(10),
     ORGANISATION_NAME         VARCHAR(100),
     FIRM_REFERENCE_NUMBER     VARCHAR(10),
     STATUS                    VARCHAR(50),
     RELATIONSHIP_TYPE_ID      VARCHAR(10),
     REGULATORY_STATUS_ID      VARCHAR(50),
     PARTY_ROLE_TYPE_ID        VARCHAR(50),
     PERM_INVESTMENT_ADVICE    DECIMAL(1,0),
     PERM_MORTGAGE_ADVICE      DECIMAL(1,0),
     PERM_INSURANCE_ADVICE     DECIMAL(1,0),
     PERM_PENSION_ADVICE       DECIMAL(1,0),
     ADDRESS_LINE_1            VARCHAR(50),
     ADDRESS_LINE_2            VARCHAR(50),
     ADDRESS_LINE_3            VARCHAR(50),
     ADDRESS_LINE_4            VARCHAR(50),
     POSTCODE                  VARCHAR(10),
     EMAIL_URL_ADDRESS         VARCHAR(100),
     PHONE_FAX_NUMBER          VARCHAR(20),
     RECORD_UPDATE_IND         VARCHAR(32),
     RECORD_DELETE_IND         DECIMAL(1,0),
     CREATE_USER_ID            VARCHAR(255),
     INSERT_DATE_TIME          DATETIME2,
     UPDATE_DATE_TIME          DATETIME2    NOT NULL
  );

IF OBJECT_ID('STAGE_CDI.DPDB_ADVISER_OFFICE_STG') IS NULL 
  CREATE TABLE STAGE_CDI.DPDB_ADVISER_OFFICE_STG
  (
     PARTY_ROLE_ID         VARCHAR(10)    NOT NULL,
     FIRM_PARTY_ROLE_ID    VARCHAR(10),
     PARTY_ROLE_NAME       VARCHAR(100),
     STATUS                VARCHAR(1),
     PARTY_ROLE_TYPE_ID    VARCHAR(10),
     ADDRESS_LINE_1        VARCHAR(50),
     ADDRESS_LINE_2        VARCHAR(50),
     ADDRESS_LINE_3        VARCHAR(50),
     ADDRESS_LINE_4        VARCHAR(50),
     POSTCODE              VARCHAR(10),
     EMAIL_URL_ADDRESS     VARCHAR(100),
     PHONE_FAX_NUMBER      VARCHAR(20),
     RECORD_UPDATE_IND     VARCHAR(32),
     RECORD_DELETE_IND     DECIMAL(1,0),
     CREATE_USER_ID        VARCHAR(255),
     INSERT_DATE_TIME      DATETIME2,
     UPDATE_DATE_TIME      DATETIME2    NOT NULL
  );

IF OBJECT_ID('STAGE_CDI.DPDB_REGISTERED_INDIVIDUAL_STG') IS NULL
  CREATE TABLE STAGE_CDI.DPDB_REGISTERED_INDIVIDUAL_STG
  (
     LEGACY_SYSTEM_ID               VARCHAR(20),
     ACCOUNT_TYPE_ID                VARCHAR(20),
     ACCOUNT_NUMBER                 VARCHAR(10)    NOT NULL,
     PARTY_ROLE_ID                  VARCHAR(10)    NOT NULL,
     OFFICE_PARTY_ROLE_ID           VARCHAR(10)    NOT NULL,
     FIRM_PARTY_ROLE_ID             VARCHAR(10)    NOT NULL,
     REL_OFFICE_PARTY_ROLE_ID       VARCHAR(10),
     REL_FIRM_PARTY_ROLE_ID         VARCHAR(10),
     TITLE_ID                       VARCHAR(10),
     FORENAME                       VARCHAR(25),
     SURNAME                        VARCHAR(25),
     INDIVIDUAL_REFERENCE_NUMBER    VARCHAR(10),
     STATUS                         VARCHAR(1),
     FIRM_REFERENCE_NUMBER          VARCHAR(10)    NOT NULL,
     ACCOUNT_STATUS                 VARCHAR(1),
     JOB_TITLE_ID                   VARCHAR(10),
     ADDRESS_LINE_1                 VARCHAR(50),
     ADDRESS_LINE_2                 VARCHAR(50),
     ADDRESS_LINE_3                 VARCHAR(50),
     ADDRESS_LINE_4                 VARCHAR(50),
     POSTCODE                       VARCHAR(10),
     RECORD_UPDATE_IND              VARCHAR(32),
     RECORD_DELETE_IND              DECIMAL(1,0),
     CREATE_USER_ID                 VARCHAR(255),
     INSERT_DATE_TIME               DATETIME2      NOT NULL,
     UPDATE_DATE_TIME               DATETIME2      NOT NULL
  );

IF OBJECT_ID('STAGE_CDI.SFDC_ADVISER_ACCOUNT_STG') IS  NULL 
  CREATE TABLE STAGE_CDI.SFDC_ADVISER_ACCOUNT_STG
  (
    SFDC_ADVISER_ACCOUNT_ID       VARCHAR(20)     NOT NULL,
    PRU_PARTYROLEID__C            VARCHAR(100)    NOT NULL,
    RECORDTYPE                    VARCHAR(40),
    NAME                          VARCHAR(255),
    PRU_STATUS__C                 VARCHAR(255),
    TYPE                          VARCHAR(255),
    PRU_FIRMREFERENCENUMBER__C    VARCHAR(10),
    PRU_REGULATORYSTATUS__C       VARCHAR(255),
    PRU_INVESTMENTADVICE__C       DECIMAL(1,0),
    PRU_MORTGAGEADVICE__C         DECIMAL(1,0),
    PRU_INSURANCEADVICE__C        DECIMAL(1,0),
    PRU_PENSIONXFERADVICE__C      DECIMAL(1,0),
    SHIPPINGSTREET                VARCHAR(255),
    SHIPPINGCITY                  VARCHAR(40),
    SHIPPINGSTATE                 VARCHAR(80),
    SHIPPINGPOSTALCODE            VARCHAR(20),
    PRU_EMAIL__C                  VARCHAR(100),
    PHONE                         VARCHAR(20),
    PRU_DATAQUALITYISSUE_C        DECIMAL(1,0),
    PRU_DATAQUALITYCOMMENT_C      VARCHAR(255),
    PRU_RECORDREMOVED__C          DECIMAL(1,0),
    PARENT                        VARCHAR(20),
    CREATE_USER_ID                VARCHAR(20),
    INSERT_DATE_TIME              DATETIME2      NOT NULL,
    UPDATE_DATE_TIME              DATETIME2      NOT NULL
  );

IF OBJECT_ID('STAGE_CDI.SFDC_ADVISER_HERITAGE_ARN_STG') IS NULL 
  CREATE TABLE STAGE_CDI.SFDC_ADVISER_HERITAGE_ARN_STG
  (
      SFDC_ADVISER_HERITAGE_ARN_ID      VARCHAR(20)    NOT NULL,
      PRU_ACCOUNT__C                    VARCHAR(20),
      PRU_HERITAGEAGENCYNUMBER__C       VARCHAR(20)    NOT NULL,
      PRU_HERITAGECONTACTRELATION__C    VARCHAR(20),
      PRU_STATUS__C                     VARCHAR(20),
      CREATE_USER_ID                    VARCHAR(255),
      INSERT_DATE_TIME                  DATETIME2,
      UPDATE_DATE_TIME                  DATETIME2      NOT NULL
  );

IF OBJECT_ID('STAGE_CDI.SFDC_ADVISER_RI_CONTACT_STG') IS NULL 
  CREATE TABLE STAGE_CDI.SFDC_ADVISER_RI_CONTACT_STG
  (
      SFDC_ADVISER_CONTACT_ID           VARCHAR(20)    NOT NULL,
      PRU_AGENCYNUMBER__C               VARCHAR(10)    NOT NULL,
      PRU_PARTYROLEID__C                VARCHAR(50)    NOT NULL,
      ACCOUNTID                         VARCHAR(20),
      SALUTATION                        VARCHAR(10),
      FIRSTNAME                         VARCHAR(40),
      LASTNAME                          VARCHAR(80),
      PRU_INDIVIDUALREFNUM__C           VARCHAR(10),
      PRU_INDIVIDUALREFNUMALT__C        VARCHAR(10),
      PRU_STATUS__C                     VARCHAR(255),
      PRU_REGISTEREDINDIVIDUALREF__C    VARCHAR(255),
      PRU_AGENCYNUMBERSTATUS__C         VARCHAR(255),
      PRU_TYPE__C                       VARCHAR(50),
      OTHERSTREET                       VARCHAR(255),
      OTHERCITY                         VARCHAR(100),
      OTHERSTATE                        VARCHAR(100),
      OTHERPOSTALCODE                   VARCHAR(20),
      PRU_DATAQUALITYISSUE__C           DECIMAL(1,0),
      PRU_DATAQUALITYCOMMENT__C         VARCHAR(255),
      PRU_RECORDREMOVED__C              DECIMAL(1,0),
      CREATE_USER_ID                    VARCHAR(255),
      INSERT_DATE_TIME                  DATETIME2      NOT NULL,
      UPDATE_DATE_TIME                  DATETIME2      NOT NULL
  );
