CREATE TYPE STAGE_CDI.DPDB_ADVISER_FIRM_STG_TYPE AS TABLE
(
    PARTY_ROLE_ID             VARCHAR(10)    NOT NULL,
    ORGANISATION_NAME         VARCHAR(100),
    FIRM_REFERENCE_NUMBER     VARCHAR(10)    NOT NULL,
    STATUS                    VARCHAR(50),
    REGULATORY_STATUS_ID      VARCHAR(50),
    PARTY_ROLE_TYPE_ID        VARCHAR(50),
    PERM_INVESTMENT_ADVICE    DECIMAL(1,0),
    PERM_MORTGAGE_ADVICE      DECIMAL(1,0),
    PERM_INSURANCE_ADVICE     DECIMAL(1,0),
    PERM_PENSION_ADVICE       DECIMAL(1,0),
    ADDRESS_LINE_1            VARCHAR(50),
    ADDRESS_LINE_2            VARCHAR(50),
    ADDRESS_LINE_3            VARCHAR(50),
    ADDRESS_LINE_4            VARCHAR(50),
    POSTCODE                  VARCHAR(10),
    EMAIL_URL_ADDRESS         VARCHAR(100),
    PHONE_FAX_NUMBER          VARCHAR(20),
    RECORD_UPDATE_IND         VARCHAR(32),
    RECORD_DELETE_IND         DECIMAL(1,0),
    CREATE_USER_ID            VARCHAR(255),
    INSERT_DATE_TIME          DATETIME2,
    UPDATE_DATE_TIME          DATETIME2    NOT NULL
);

CREATE TYPE STAGE_CDI.DPDB_ADVISER_LEGACY_AGENCY_STG_TYPE AS TABLE
(
    ACCOUNT_NUMBER              VARCHAR(10)    NOT NULL,
    OFFICE_PARTY_ROLE_ID        VARCHAR(10),
    FIRM_PARTY_ROLE_ID          VARCHAR(10),
    ACCOUNT_STATUS              VARCHAR(1),
    OFFICE_STATUS               VARCHAR(1),
    PARTY_ROLE_TYPE_ID          VARCHAR(10),
    INDIVIDUAL_PARTY_ROLE_ID    VARCHAR(10),
    ACCOUNT_TYPE_ID             VARCHAR(20),
    LEGACY_SYSTEM_ID            VARCHAR(20),
    RECORD_UPDATE_IND           VARCHAR(32),
    RECORD_DELETE_IND           DECIMAL(1,0),
    CREATE_USER_ID              VARCHAR(255),
    INSERT_DATE_TIME            DATETIME2,
    UPDATE_DATE_TIME            DATETIME2    NOT NULL
);

CREATE TYPE STAGE_CDI.DPDB_ADVISER_NETWORK_STG_TYPE AS TABLE
(
    NETWORK_PARTY_ROLE_ID     VARCHAR(10)    NOT NULL,
    REL_FIRM_PARTY_ROLE_ID    VARCHAR(10),
    ORGANISATION_NAME         VARCHAR(100),
    FIRM_REFERENCE_NUMBER     VARCHAR(10),
    STATUS                    VARCHAR(50),
    RELATIONSHIP_TYPE_ID      VARCHAR(10),
    REGULATORY_STATUS_ID      VARCHAR(50),
    PARTY_ROLE_TYPE_ID        VARCHAR(50),
    PERM_INVESTMENT_ADVICE    DECIMAL(1,0),
    PERM_MORTGAGE_ADVICE      DECIMAL(1,0),
    PERM_INSURANCE_ADVICE     DECIMAL(1,0),
    PERM_PENSION_ADVICE       DECIMAL(1,0),
    ADDRESS_LINE_1            VARCHAR(50),
    ADDRESS_LINE_2            VARCHAR(50),
    ADDRESS_LINE_3            VARCHAR(50),
    ADDRESS_LINE_4            VARCHAR(50),
    POSTCODE                  VARCHAR(10),
    EMAIL_URL_ADDRESS         VARCHAR(100),
    PHONE_FAX_NUMBER          VARCHAR(20),
    RECORD_UPDATE_IND         VARCHAR(32),
    RECORD_DELETE_IND         DECIMAL(1,0),
    CREATE_USER_ID            VARCHAR(255),
    INSERT_DATE_TIME          DATETIME2,
    UPDATE_DATE_TIME          DATETIME2    NOT NULL
);

CREATE TYPE STAGE_CDI.DPDB_ADVISER_OFFICE_STG_TYPE AS TABLE
(
    PARTY_ROLE_ID         VARCHAR(10)    NOT NULL,
    FIRM_PARTY_ROLE_ID    VARCHAR(10),
    PARTY_ROLE_NAME       VARCHAR(50),
    STATUS                VARCHAR(1),
    PARTY_ROLE_TYPE_ID    VARCHAR(10),
    ADDRESS_LINE_1        VARCHAR(50),
    ADDRESS_LINE_2        VARCHAR(50),
    ADDRESS_LINE_3        VARCHAR(50),
    ADDRESS_LINE_4        VARCHAR(50),
    POSTCODE              VARCHAR(10),
    EMAIL_URL_ADDRESS     VARCHAR(100),
    PHONE_FAX_NUMBER      VARCHAR(20),
    RECORD_UPDATE_IND     VARCHAR(32),
    RECORD_DELETE_IND     DECIMAL(1,0),
    CREATE_USER_ID        VARCHAR(255),
    INSERT_DATE_TIME      DATETIME2,
    UPDATE_DATE_TIME      DATETIME2    NOT NULL
);

CREATE TYPE STAGE_CDI.DPDB_REGISTERED_INDIVIDUAL_STG_TYPE AS TABLE
(
    LEGACY_SYSTEM_ID               VARCHAR(20),
    ACCOUNT_TYPE_ID                VARCHAR(20),
    ACCOUNT_NUMBER                 VARCHAR(10)    NOT NULL,
    PARTY_ROLE_ID                  VARCHAR(10)    NOT NULL,
    OFFICE_PARTY_ROLE_ID           VARCHAR(10)    NOT NULL,
    FIRM_PARTY_ROLE_ID             VARCHAR(10)    NOT NULL,
    REL_OFFICE_PARTY_ROLE_ID       VARCHAR(10),
    REL_FIRM_PARTY_ROLE_ID         VARCHAR(10),
    TITLE_ID                       VARCHAR(10),
    FORENAME                       VARCHAR(25),
    SURNAME                        VARCHAR(25),
    INDIVIDUAL_REFERENCE_NUMBER    VARCHAR(10),
    STATUS                         VARCHAR(1),
    FIRM_REFERENCE_NUMBER          VARCHAR(10)    NOT NULL,
    ACCOUNT_STATUS                 VARCHAR(1),
    JOB_TITLE_ID                   VARCHAR(10),
    ADDRESS_LINE_1                 VARCHAR(50),
    ADDRESS_LINE_2                 VARCHAR(50),
    ADDRESS_LINE_3                 VARCHAR(50),
    ADDRESS_LINE_4                 VARCHAR(50),
    POSTCODE                       VARCHAR(10),
    RECORD_UPDATE_IND              VARCHAR(32),
    RECORD_DELETE_IND              DECIMAL(1,0),
    CREATE_USER_ID                 VARCHAR(255),
    INSERT_DATE_TIME               DATETIME2    NOT NULL,
    UPDATE_DATE_TIME               DATETIME2    NOT NULL
);