CREATE TRIGGER TRG_BATCH_PARAMETER
	ON STAGE_CDI.BATCH_PARAMETER
	AFTER INSERT, UPDATE, DELETE
AS
BEGIN
  SET NOCOUNT ON;

  INSERT
    INTO STAGE_CDI.BATCH_PARAMETER_HIST
         (PROCESS_NAME,
		  PARAMETER_NAME,
		  PARAMETER_VALUE_DT,
		  PARAMETER_VALUE_NUMBER,
		  PARAMETER_VALUE_CHAR,
		  LASTMODIFIEDDT,
		  LASTMODIFIEDBY,
		  ACTION_TYPE,
		  ACTIONED_BY,
		  ACTION_DATE)
    SELECT ISNULL(I.PROCESS_NAME, D.PROCESS_NAME) AS PROCESS_NAME,
	       ISNULL(I.PARAMETER_NAME, D.PARAMETER_NAME) AS PARAMETER_NAME,
	       ISNULL(I.PARAMETER_VALUE_DT, D.PARAMETER_VALUE_DT) AS PARAMETER_VALUE_DT,
		   ISNULL(I.PARAMETER_VALUE_NUMBER, D.PARAMETER_VALUE_NUMBER) AS PARAMETER_VALUE_NUMBER,
		   ISNULL(I.PARAMETER_VALUE_CHAR, D.PARAMETER_VALUE_CHAR) AS PARAMETER_VALUE_CHAR,
		   ISNULL(I.LASTMODIFIEDDT, D.LASTMODIFIEDDT) AS LASTMODIFIEDDT,
		   ISNULL(I.LASTMODIFIEDBY, D.LASTMODIFIEDBY) AS LASTMODIFIEDBY,
		   CASE
		     WHEN I.PROCESS_NAME IS NULL THEN
			   'DELETE'
			 WHEN D.PROCESS_NAME IS NULL THEN
			   'INSERT'
		   ELSE
		     'UPDATE'
		   END AS ACTION_TYPE,
		   SUSER_SNAME() AS ACTIONED_BY,
		   CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'GMT STANDARD TIME' AS DATETIME) AS ACTION_DATE
	  FROM INSERTED I
	  FULL OUTER JOIN DELETED D 
	    ON (    I.PROCESS_NAME = D.PROCESS_NAME
		    AND I.PARAMETER_NAME = D.PARAMETER_NAME)
END