IF OBJECT_ID('Z_ADF_SFDC.BATCH_PARAMETER') IS NULL 
  CREATE TABLE Z_ADF_SFDC.BATCH_PARAMETER
  (
    PROCESS_NAME              VARCHAR(255)   NOT NULL,
    PARAMETER_NAME            VARCHAR(255)   NOT NULL,
	PARAMETER_VALUE_DT        DATETIME2,
	PARAMETER_VALUE_NUMBER    INT,
	PARAMETER_VALUE_CHAR      VARCHAR(400),
	LASTMODIFIEDDT            DATETIME2      NOT NULL,
	LASTMODIFIEDBY            VARCHAR(255)   NOT NULL,
	CONSTRAINT BATCH_PARAMETER_PK PRIMARY KEY (PROCESS_NAME, PARAMETER_NAME)
  );