IF OBJECT_ID('STAGE_CDI.BATCH_FUNCTION_FREQUENCY') IS NULL
  CREATE TABLE STAGE_CDI.BATCH_FUNCTION_FREQUENCY
  (
    FREQUENCY_ID      INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    FUNCTION_AREA     VARCHAR(255)      NOT NULL,
    FREQUENCY         SMALLINT          NOT NULL,
    FREQUENCY_UNIT    VARCHAR(50),
    BATCH             VARCHAR(50),
    START_TIME        TIME,
    END_TIME          TIME,
    RUN_DAYS          VARCHAR(50),
    START_DAY         SMALLINT,
    END_DAY           SMALLINT,
    RUN_MONTHS        VARCHAR(50)
  );