IF OBJECT_ID('STAGE_CDI.BATCH_FUNCTION_FREQUENCY') IS NULL
  CREATE TABLE STAGE_CDI.BATCH_FUNCTION_FREQUENCY
  (
    FREQUENCY_ID    INT              PRIMARY KEY,
    FREQUENCY       VARCHAR(255),
    BATCH           VARCHAR(255),
    START_TIME      TIME,
    END_TIME        TIME,
    START_DAY       VARCHAR(50),
    END_DAY         VARCHAR(50)
  );