CREATE TABLE [STAGE_LOAD].TD_CENTERA_OSDB_THUNDERHEAD_MAILPACK_STG
(
    DOCUMENT_ID     varchar(20),             
    PRINT_STREAM_ID       VARCHAR(50)  ,
    RECIPIENT_TYPE        VARCHAR(50)  ,
    PRINT_SUPPRESSED      VARCHAR(10)  ,
    ARCHETYPE_NAME       VARCHAR(50) ,
    ARCHETYPE_GROUP      VARCHAR(50) ,
    STATUS_ID               int ,      
    STATUS_TIMESTAMP       [datetime2](6) ,
    STATUS_CODE          VARCHAR(256),
    STATUS_DESC          VARCHAR(256),
    OCDB_PARTY_ROLE_ID     int  ,    
    CREATE_USER_ID varchar(50), -- 'IICSBATCH',
    STG_CREATE_DATETIME DATETIME --
	

);


CREATE INDEX TD_CENTERA_OSDB_THUNDERHEAD_MAILPACK_IDX1 ON [STAGE_LOAD].TD_CENTERA_OSDB_THUNDERHEAD_MAILPACK_STG (DOCUMENT_ID);




CREATE TABLE [STAGE_LOAD].TD_CENTERA_DOCMAN_DOCUMENT_INDEX_STG
(
    DOCUMENT_ID     varchar(20),             
    DOCUMENT_CLIP_ID   varchar(100),          
    COMMITTAL_DT           DATE,          
    INDEX_FIELD_ID     	int,   
    INDEX_VALUE             varchar(100),           
    DOCUMENT_GROUP_ID         int,      
    DATA_ACCESS_CLASS_DESCRIPTION   varchar(100),     
    DOCUMENT_FORMAT_DESCRIPTION varchar(100),     
    DOCUMENT_TYPE_DESCRIPTION varchar(100),
    CREATE_USER_ID varchar(50), -- 'IICSBATCH',
    STG_CREATE_DATETIME DATE --


);


CREATE INDEX TD_CENTERA_DOCMAN_DOCUMENT_INDEX_STG_IDX1 ON [STAGE_LOAD].TD_CENTERA_DOCMAN_DOCUMENT_INDEX_STG (DOCUMENT_ID);