IF OBJECT_ID('STAGE_CDI.CRM_PLAT_DYN_ACTIVITYPARTY_STG') IS NOT NULL
  DROP TABLE STAGE_CDI.CRM_PLAT_DYN_ACTIVITYPARTY_STG;

CREATE TABLE STAGE_CDI.CRM_PLAT_DYN_ACTIVITYPARTY_STG
(
  S_ACTIVITYPARTY_KEY       DECIMAL(38,0)       NOT NULL    IDENTITY(1,1),
  S_CREATE_DATETIME         DATETIME2           NOT NULL,
  S_UPDATE_DATETIME         DATETIME2           NOT NULL,
  ACTIVITYPARTYID           VARCHAR(255)        NOT NULL,
  ACTIVITYID                VARCHAR(255)        NOT NULL,
  PARTYID                   VARCHAR(255),       
  PARTYOBJECTTYPECODE       DECIMAL(10,0)       NOT NULL,
  PARTICIPATIONTYPEMASK     DECIMAL(10,0)       NOT NULL,
  ADDRESSUSED               NVARCHAR(400),        
  DONOTEMAIL                DECIMAL(1,0),       
  DONOTFAX                  DECIMAL(1,0),       
  DONOTPOSTALMAIL           DECIMAL(1,0),       
  DONOTPHONE                DECIMAL(1,0),       
  PARTYIDDSC                DECIMAL(10,0)       NOT NULL,
  PARTYIDNAME               NVARCHAR(200),        
  ISPARTYDELETED            DECIMAL(1,0)        NOT NULL,
  EXCHANGEENTRYID           NVARCHAR(544),        
  EFFORT                    DECIMAL(10,0),      
  INSTANCETYPECODE          DECIMAL(10,0),      
  RESOURCESPECID            VARCHAR(255),         
  RESOURCESPECIDNAME        NVARCHAR(350),        
  RESOURCESPECIDDSC         DECIMAL(10,0)       NOT NULL,
  SCHEDULEDSTART            DATETIME2,          
  SCHEDULEDEND              DATETIME2,          
  OWNINGUSER                VARCHAR(255),       
  OWNERID                   VARCHAR(255),       
  OWNERIDTYPE               DECIMAL(10,0),    
  OWNINGBUSINESSUNIT        VARCHAR(255)
);

ALTER TABLE STAGE_CDI.CRM_PLAT_DYN_ACTIVITYPARTY_STG 
  ADD CONSTRAINT DF_CRM_PLAT_DYN_ACTIVITYPARTY_STG_S_CREATE_DATETIME DEFAULT CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'GMT Standard Time' AS DATETIME2) FOR S_CREATE_DATETIME ; 

ALTER TABLE STAGE_CDI.CRM_PLAT_DYN_ACTIVITYPARTY_STG 
  ADD CONSTRAINT DF_CRM_PLAT_DYN_ACTIVITYPARTY_STG_S_UPDATE_DATETIME DEFAULT CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'GMT Standard Time' AS DATETIME2) FOR S_UPDATE_DATETIME ; 
  