IF OBJECT_ID('STAGE_CDI.CRM_PLAT_DYN_INCIDENT_STG') IS NULL
BEGIN
  CREATE TABLE STAGE_CDI.CRM_PLAT_DYN_INCIDENT_STG
  (
     S_CREATE_DATETIME                        DATETIME2(7)        NOT NULL,
     S_UPDATE_DATETIME                        DATETIME2(7)        NOT NULL,
     INCIDENTID                               VARCHAR(255)        NOT NULL,
     TICKETNUMBER                             NVARCHAR(400)       NOT NULL,
     CASETYPECODE                             DECIMAL(10, 0),
     SUBJECTIDNAME                            NVARCHAR(2000),
     OWNERIDNAME                              NVARCHAR(640),
     CASEORIGINCODE                           DECIMAL(10, 0),
     NEW_CASESTATUS                           DECIMAL(10, 0),
     TITLE                                    NVARCHAR(800),
     DESCRIPTION                              VARCHAR(MAX),
     CREATEDON                                DATETIME2(7),
     ASC_DATECLOSED                           DATETIME2(7),
     ASC_DATESETONHOLD                        DATETIME2(7),
     CREATEDBYNAME                            NVARCHAR(800),
     MODIFIEDON                               DATETIME2(7),
     MODIFIEDBYNAME                           NVARCHAR(800),
     ASC_BROKERID                             VARCHAR(255),
     ASC_BROKERIDNAME                         NVARCHAR(640),
     ASC_CANNOTBESTARTEDSETDATE               DATETIME2(7),
     ASC_CASETYPE                             DECIMAL(10, 0),
     ASC_CHARITY                              DECIMAL(1, 0),
     ASC_CLEANAPPLICATION                     DECIMAL(1, 0),
     ASC_COMPLAINTID                          VARCHAR(255),
     ASC_COMPLAINTIDNAME                      NVARCHAR(80),
     ASC_CORPORATE                            DECIMAL(1, 0),
     ASC_DATAPROTECTIONCHECK                  DECIMAL(10, 0),
     ASC_DATERECEIVED                         DATETIME2(7),
     ASC_DATEWORKSTARTEDONCASE                DATETIME2(7),
     ASC_DAYSONHOLD                           DECIMAL(10, 0),
     ASC_DAYSONHOLDCURRENT                    DECIMAL(10, 0),
     ASC_ENHANCEDDATACHECKS                   DECIMAL(10, 0),
     ASC_GIA                                  DECIMAL(1, 0),
     ASC_ISA                                  DECIMAL(1, 0),
     ASC_ISCASERESOLVED                       DECIMAL(1, 0),
     ASC_ITHELPDESKRAISED                     DECIMAL(1, 0),
     ASC_JISA                                 DECIMAL(1, 0),
     ASC_NUMBEROFCLIENTS                      DECIMAL(10, 0),
     ASC_ONEANDDONE                           DECIMAL(1, 0),
     ASC_ONETOUCH                             DECIMAL(1, 0),
     ASC_ONHOLD                               DECIMAL(1, 0),
     ASC_OTHER                                DECIMAL(1, 0),
     ASC_PENDINGREASON                        DECIMAL(10, 0),
     ASC_REASONAPPLICATIONUNCLEAN             DECIMAL(10, 0),
     ASC_REASONDPACHECKNOTAPPLICABLE          VARCHAR(MAX),
     ASC_RECEIVEDAFTER3PM                     DECIMAL(1, 0),
     ASC_ROOTCAUSE                            DECIMAL(10, 0),
     ASC_SETONHOLDBYID                        VARCHAR(255),
     ASC_SETONHOLDBYIDNAME                    NVARCHAR(800),
     ASC_SLADATE                              DATETIME2(7),
     ASC_SUBJECT                              DECIMAL(10, 0),
     ASC_TAKENOFFFROMHOLD                     DATETIME2(7),
     ASC_TEAMSLADATE                          DATETIME2(7),
     ASC_TRUST                                DECIMAL(1, 0),
     ASC_WORKINGDAYS                          NVARCHAR(80),
     CREATEDBY                                VARCHAR(255),
     CUSTOMERID                               VARCHAR(255),
     CUSTOMERIDNAME                           NVARCHAR(1000),
     MODIFIEDBY                               VARCHAR(255),
     NEW_ADVISER                              VARCHAR(255),
     NEW_ADVISERNAME                          NVARCHAR(640),
     NEW_BDM                                  VARCHAR(255),
     NEW_BDMNAME                              NVARCHAR(800),
     NEW_DATEACKNOWLEDGED                     DATETIME2(7),
     NEW_EMAILTOCASEBODYRAW                   VARCHAR(MAX),
     NEW_EMAILTOCASEBODYTEXT                  VARCHAR(MAX),
     NEW_EMAILTOCASEQUEUE                     NVARCHAR(800),
     NEW_REFERENCEACCEXECTEAMID               VARCHAR(255),
     NEW_REFERENCEACCEXECTEAMIDNAME           NVARCHAR(640),
     NEW_REFERENCEASCENTRICCRMSERVERID        VARCHAR(255),
     NEW_REFERENCEASCENTRICCRMSERVERIDNAME    NVARCHAR(400),
     OWNERID                                  VARCHAR(255),
     SUBJECTID                                VARCHAR(255),
     S_INCIDENT_KEY                           BIGINT,
     ASC_SIPP                                 NUMERIC(1, 0),
     ASC_THIRDPARTY                           NUMERIC(1, 0),
     STATUSCODE                               NUMERIC(10, 0),
     STATECODE                                NUMERIC(10, 0)
   );
   
   ALTER TABLE STAGE_CDI.CRM_PLAT_DYN_INCIDENT_STG 
     ADD CONSTRAINT DF_CRM_PLAT_DYN_INCIDENT_STG_S_CREATE_DATETIME  DEFAULT (CONVERT(DATETIME2,(SYSDATETIMEOFFSET() AT TIME ZONE 'GMT STANDARD TIME'))) FOR S_CREATE_DATETIME;

   ALTER TABLE STAGE_CDI.CRM_PLAT_DYN_INCIDENT_STG 
     ADD CONSTRAINT DF_CRM_PLAT_DYN_INCIDENT_STG_S_UPDATE_DATETIME  DEFAULT (CONVERT(DATETIME2,(SYSDATETIMEOFFSET() AT TIME ZONE 'GMT STANDARD TIME'))) FOR S_UPDATE_DATETIME;

   ALTER TABLE STAGE_CDI.CRM_PLAT_DYN_INCIDENT_STG
     ADD CONSTRAINT CRM_PLAT_DYN_INCIDENT_STG_PK PRIMARY KEY (INCIDENTID);
  
END;
