IF OBJECT_ID('STAGE_CDI.CRM_PLAT_DYN_DIVORCECLAIM_STG') IS NOT NULL
  DROP TABLE STAGE_CDI.CRM_PLAT_DYN_DIVORCECLAIM_STG;

CREATE TABLE STAGE_CDI.CRM_PLAT_DYN_DIVORCECLAIM_STG
(
  S_DIVORCECLAIM_KEY                  DECIMAL(38,0)    NOT NULL    IDENTITY(1,1),
  S_CREATE_DATETIME                   DATETIME2	       NOT NULL,
  S_UPDATE_DATETIME                   DATETIME2        NOT NULL,
  ACTIVITYID                          VARCHAR(255)     NOT NULL,
  PRIORITYCODE                        DECIMAL(10,0),
  SCHEDULEDEND                        DATETIME2,
  STATECODE                           DECIMAL(10,0),
  OWNERID                             VARCHAR(255),
  OWNERIDNAME                         VARCHAR(160),
  SUBJECT                             VARCHAR(200),
  REGARDINGOBJECTID                   VARCHAR(255),
  ASC_CASETYPE                        DECIMAL(10,0),
  ASC_IFAFIRM                         VARCHAR(255),
  ASC_REGISTEREDIFA                   VARCHAR(255),
  ASC_BROKER                          VARCHAR(255),
  ASC_CLIENTMASTER                    VARCHAR(255),
  ACTUALSTART                         DATETIME2,
  MODIFIEDON                          DATETIME2,
  ASC_DURATION                        VARCHAR(100),
  CREATEDBY                           VARCHAR(255),
  CREATEDBYNAME                       VARCHAR(200),
  ASC_COMPLETEDBY_DRNAME              VARCHAR(200),
  ASC_COMPLETEDBY_SETTLEMENTNAME      VARCHAR(200),
  ASC_CHECKEDBYNAME                   VARCHAR(200),
  ASC_COMPLETEDBYNAME                 VARCHAR(200),
  ASC_CHECKEDBY                       VARCHAR(255),
  ASC_COMPLETEDBY                     VARCHAR(255),
  ASC_COMPLETEDBY_DR                  VARCHAR(255),
  ASC_COMPLETEDBY_SETTLEMENT          VARCHAR(255),
  ASC_ADVISERREQUESTEDTOPLACESALES    DECIMAL(1,0),
  ASC_AMOUNTDUE                       DECIMAL(19,4),
  ASC_DATECOMPLETED                   DATETIME2,
  ASC_DATENOTIFIED                    DATETIME2,
  ASC_DATEPROCESSED                   DATETIME2,
  ASC_DATEPROCESSED_DR                DATETIME2,
  ASC_DATEPROCESSED_SETTLEMENT        DATETIME2,
  ASC_DATERECEIVED                    DATETIME2,
  ASC_DATEUSEDFORPSO                  DATETIME2,
  ASC_DECREEABSOLUTERECEIVED          DECIMAL(1,0),
  ASC_EXTERNALPAYMENTRAISED           DECIMAL(1,0),
  ASC_FEESDEDUCTED                    DECIMAL(1,0),
  ASC_INTERNALBALANCETRANSFERRED      DECIMAL(1,0),
  ASC_PENSIONENQUIRYFORMRECEIVED      DECIMAL(1,0),
  ASC_PENSIONSHARINGANNEX             DECIMAL(1,0),
  ASC_PENSIONSHARINGORDERRECEIVED     DECIMAL(1,0),
  ASC_PERCENTAGEOFACCOUNT             DECIMAL(38,0),
  ASC_RECEIVINGSCHEME                 VARCHAR(100),
  ASC_RELEVANTDOCUMENTSRECEIVED       DECIMAL(1,0),
  ASC_REQUIREMENTLETTEREMAILISSUED    DECIMAL(1,0),
  ASC_WHONOTIFIEDUS                   VARCHAR(100),
  ASC_REFERENCE                       VARCHAR(255),
  ASC_CLIENTMASTERNAME                VARCHAR(255),
  REAGRDINGOBJECTIDNAME               VARCHAR(255)
  );
  
  ALTER TABLE STAGE_CDI.CRM_PLAT_DYN_DIVORCECLAIM_STG 
  ADD CONSTRAINT DF_CRM_PLAT_DYN_DIVORCECLAIM_STG_S_CREATE_DATETIME DEFAULT CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'GMT Standard Time' AS DATETIME2) FOR S_CREATE_DATETIME ; 

ALTER TABLE STAGE_CDI.CRM_PLAT_DYN_DIVORCECLAIM_STG 
  ADD CONSTRAINT DF_CRM_PLAT_DYN_DIVORCECLAIM_STG_S_UPDATE_DATETIME DEFAULT CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'GMT Standard Time' AS DATETIME2) FOR S_UPDATE_DATETIME ; 
