IF OBJECT_ID('STAGE_LOAD.TD_DPDB_ADVISER_FIRM_STG') IS NOT NULL 
  DROP TABLE STAGE_LOAD.TD_DPDB_ADVISER_FIRM_STG;

CREATE TABLE STAGE_LOAD.TD_DPDB_ADVISER_FIRM_STG
(
    PARTY_ROLE_ID             VARCHAR(10)    NOT NULL,
    ORGANISATION_NAME         VARCHAR(100),
    FIRM_REFERENCE_NUMBER     VARCHAR(10)    NOT NULL,
    STATUS                    VARCHAR(50),
    REGULATORY_STATUS_ID      VARCHAR(50),
    PARTY_ROLE_TYPE_ID        VARCHAR(50),
    PERM_INVESTMENT_ADVICE    DECIMAL(1,0),
    PERM_MORTGAGE_ADVICE      DECIMAL(1,0),
    PERM_INSURANCE_ADVICE     DECIMAL(1,0),
    PERM_PENSION_ADVICE       DECIMAL(1,0),
    ADDRESS_LINE_1            VARCHAR(50),
    ADDRESS_LINE_2            VARCHAR(50),
    ADDRESS_LINE_3            VARCHAR(50),
    ADDRESS_LINE_4            VARCHAR(50),
    POSTCODE                  VARCHAR(10),
    EMAIL_URL_ADDRESS         VARCHAR(100),
    PHONE_FAX_NUMBER          VARCHAR(20)
);

IF OBJECT_ID('STAGE_LOAD.TD_DPDB_ADVISER_LEGACY_AGENCY_STG') IS NOT NULL 
  DROP TABLE STAGE_LOAD.TD_DPDB_ADVISER_LEGACY_AGENCY_STG;

CREATE TABLE STAGE_LOAD.TD_DPDB_ADVISER_LEGACY_AGENCY_STG
(
	ACCOUNT_NUMBER              VARCHAR(10) NOT NULL,
	OFFICE_PARTY_ROLE_ID        VARCHAR(10),
	FIRM_PARTY_ROLE_ID          VARCHAR(10),
	ACCOUNT_STATUS              VARCHAR(1),
	OFFICE_STATUS               VARCHAR(1),
	PARTY_ROLE_TYPE_ID          VARCHAR(10),
	INDIVIDUAL_PARTY_ROLE_ID    VARCHAR(10),
	ACCOUNT_TYPE_ID             VARCHAR(20),
	LEGACY_SYSTEM_ID            VARCHAR(20)
);

IF OBJECT_ID('STAGE_LOAD.TD_DPDB_ADVISER_NETWORK_STG') IS NOT NULL 
  DROP TABLE STAGE_LOAD.TD_DPDB_ADVISER_NETWORK_STG;

CREATE TABLE STAGE_LOAD.TD_DPDB_ADVISER_NETWORK_STG
(
    NETWORK_PARTY_ROLE_ID     VARCHAR(10)    NOT NULL,
    REL_FIRM_PARTY_ROLE_ID    VARCHAR(10),
    ORGANISATION_NAME         VARCHAR(100),
    FIRM_REFERENCE_NUMBER     VARCHAR(10),
    STATUS                    VARCHAR(50),
    RELATIONSHIP_TYPE_ID      VARCHAR(10),
    REGULATORY_STATUS_ID      VARCHAR(50),
    PARTY_ROLE_TYPE_ID        VARCHAR(50),
    PERM_INVESTMENT_ADVICE    DECIMAL(1,0),
    PERM_MORTGAGE_ADVICE      DECIMAL(1,0),
    PERM_INSURANCE_ADVICE     DECIMAL(1,0),
    PERM_PENSION_ADVICE       DECIMAL(1,0),
    ADDRESS_LINE_1            VARCHAR(50),
    ADDRESS_LINE_2            VARCHAR(50),
    ADDRESS_LINE_3            VARCHAR(50),
    ADDRESS_LINE_4            VARCHAR(50),
    POSTCODE                  VARCHAR(10),
    EMAIL_URL_ADDRESS         VARCHAR(100),
    PHONE_FAX_NUMBER          VARCHAR(20)
);

IF OBJECT_ID('STAGE_LOAD.TD_DPDB_ADVISER_OFFICE_STG') IS NOT NULL 
  DROP TABLE STAGE_LOAD.TD_DPDB_ADVISER_OFFICE_STG;

CREATE TABLE STAGE_LOAD.TD_DPDB_ADVISER_OFFICE_STG
(
	PARTY_ROLE_ID          VARCHAR(10) NOT NULL,
	FIRM_PARTY_ROLE_ID     VARCHAR(10),
	PARTY_ROLE_NAME        VARCHAR(50),
	UPDATED_DATE           DATETIME2,
	STATUS                 VARCHAR(1), 
	PARTY_ROLE_TYPE_ID     VARCHAR(10),
	ADDRESS_LINE_1         VARCHAR(50),
	ADDRESS_LINE_2         VARCHAR(50),
	ADDRESS_LINE_3         VARCHAR(50),
	ADDRESS_LINE_4         VARCHAR(50),
	POSTCODE               VARCHAR(10),
	EMAIL_URL_ADDRESS      VARCHAR(100),
	PHONE_FAX_NUMBER       VARCHAR(20)
);

IF OBJECT_ID('STAGE_LOAD.TD_SFDC_ADVISER_ACCOUNT_STG') IS NOT NULL 
  DROP TABLE STAGE_LOAD.TD_SFDC_ADVISER_ACCOUNT_STG;
  
CREATE TABLE STAGE_LOAD.TD_SFDC_ADVISER_ACCOUNT_STG
(
  ID                                       VARCHAR(20),
  PRU_PARTYROLEID__C                       VARCHAR(100),
  RECORDTYPEID                             VARCHAR(40),
  NAME                                     VARCHAR(255),
  PRU_STATUS__C                            VARCHAR(255),
  TYPE                                     VARCHAR(255),
  PRU_FIRMREFERENCENUMBER__C               VARCHAR(10),
  PRU_REGULATORYSTATUS__C                  VARCHAR(255),
  PRU_PERMISSIONFORINVESTMENTADVICE__C     VARCHAR(255),
  PRU_PERMISSIONFORMORTGAGEADVICE__C       VARCHAR(255),
  PRU_PERMISSIONFORINSURANCEADVICE__C      VARCHAR(255),
  PRU_PERMISSIONFORPENSIONXFERADVICE__C    VARCHAR(255),
  SHIPPINGSTREET                           VARCHAR(255),
  SHIPPINGCITY                             VARCHAR(40),
  SHIPPINGSTATE                            VARCHAR(80),
  SHIPPINGPOSTALCODE                       VARCHAR(20),
  PRU_EMAIL__C                             VARCHAR(100),
  PHONE                                    VARCHAR(20),
  PRU_DATAQUALITYISSUE__C                  VARCHAR(100),
  PRU_DATAQUALITYCOMMENT__C                VARCHAR(255),
  PRU_RECORDREMOVED__C                     VARCHAR(255),
  PARENTID                                 VARCHAR(20),
  LASTMODIFIEDDATE                         DATETIME2(7)
);

IF OBJECT_ID('STAGE_LOAD.TD_SFDC_ADVISER_HERITAGE_ARN_STG') IS NOT NULL 
  DROP TABLE STAGE_LOAD.TD_SFDC_ADVISER_HERITAGE_ARN_STG;

CREATE TABLE STAGE_LOAD.TD_SFDC_ADVISER_HERITAGE_ARN_STG 
(
  ID                               VARCHAR(20)    NOT NULL,
  PRU_ACCOUNT__C                   VARCHAR(20),
  PRU_HERITAGEAGENCYNUMBER__C      VARCHAR(20)    NOT NULL,
  PRU_HERITAGECONTACTRELATION__C   VARCHAR(20),
  PRU_STATUS__C                    VARCHAR(20),
  LASTMODIFIEDDATE                 DATETIME2
);

IF OBJECT_ID('STAGE_LOAD.TD_SFDC_ADVISER_RI_CONTACT_STG') IS NOT NULL 
  DROP TABLE STAGE_LOAD.TD_SFDC_ADVISER_RI_CONTACT_STG;
  
CREATE TABLE STAGE_LOAD.TD_SFDC_ADVISER_RI_CONTACT_STG
(
	ID                                      VARCHAR(20),
	PRU_PARTYROLEID__C                      VARCHAR(50),
	ACCOUNTID                               VARCHAR(20),
	SALUTATION                              VARCHAR(10),
	FIRSTNAME                               VARCHAR(40),
	LASTNAME                                VARCHAR(80),
	PRU_INDIVIDUALREFERENCENUMBER__C        VARCHAR(10),
	PRU_INDIVIDUALREFERENCENUMBERALT__C     VARCHAR(10),
	PRU_STATUS__C                           VARCHAR(255),
	PRU_REGISTEREDINDIVIDUALREFERENCE__C    VARCHAR(255),
	PRU_AGENCYNUMBER__C                     VARCHAR(255),
	PRU_AGENCYNUMBERSTATUS__C               VARCHAR(50),
	PRU_TYPE__C                             VARCHAR(50),
	OTHERSTREET                             VARCHAR(255),
	OTHERCITY                               VARCHAR(100),
	OTHERSTATE                              VARCHAR(100),
	PRU_DATAQUALITYISSUE__C                 INT,
	PRU_DATAQUALITYCOMMENT__C               VARCHAR(255),
	OTHERPOSTALCODE                         VARCHAR(20),
	PRU_RECORDREMOVED__C                    INT,
	LASTMODIFIEDDATE                        DATETIME2
);

IF OBJECT_ID('STAGE_LOAD.TD_DPDB_REGISTERED_INDIVIDUAL_STG') IS NOT NULL 
  DROP TABLE STAGE_LOAD.TD_DPDB_REGISTERED_INDIVIDUAL_STG;
  
CREATE TABLE STAGE_LOAD.TD_DPDB_REGISTERED_INDIVIDUAL_STG
(
   LEGACY_SYSTEM_ID               varchar(20),
   ACCOUNT_TYPE_ID                varchar(20),
   ACCOUNT_NUMBER                 varchar(10)   NOT NULL,
   PARTY_ROLE_ID                  varchar(10)   NOT NULL,
   OFFICE_PARTY_ROLE_ID           varchar(10)   NOT NULL,
   FIRM_PARTY_ROLE_ID             varchar(10)   NOT NULL,
   REL_OFFICE_PARTY_ROLE_ID       varchar(10),
   REL_FIRM_PARTY_ROLE_ID         varchar(10),
   TITLE_ID                       varchar(10),
   FORENAME                       varchar(25),
   SURNAME                        varchar(25),
   INDIVIDUAL_REFERENCE_NUMBER    varchar(10),
   STATUS                         varchar(1),
   FIRM_REFERENCE_NUMBER          varchar(10)   NOT NULL,
   ACCOUNT_STATUS                 varchar(1),
   JOB_TITLE_ID                   varchar(10),
   ADDRESS_LINE_1                 varchar(50),
   ADDRESS_LINE_2                 varchar(50),
   ADDRESS_LINE_3                 varchar(50),
   ADDRESS_LINE_4                 varchar(50),
   POSTCODE                       varchar(10)
);