--
-- The following entries are required for delta processing of related ADF 
-- pipelines. This SQL should only be deployed once the ETL_JOB_CONTROL table
-- from STAGE_CRM has been populated
--
-- Remove any old entries
--
delete
 from STAGE_CDI.BATCH_PARAMETER
where PROCESS_NAME = 'p_CDI-SFDC-ACCOUNT-ADVISER_NETWORK';

delete
 from STAGE_CDI.BATCH_PARAMETER
where PROCESS_NAME = 'p_CDI-SFDC-ACCOUNT-ADVISER_FIRM';

delete
 from STAGE_CDI.BATCH_PARAMETER
where PROCESS_NAME = 'p_SFDC-CDI-SFDC_ADVISER_ACCOUNT_STG';

delete
 from STAGE_CDI.BATCH_PARAMETER
where PROCESS_NAME = 'p_CDI-SFDC-ACCOUNT-ADVISER_OFFICE';

delete
 from STAGE_CDI.BATCH_PARAMETER
where PROCESS_NAME = 'p_CDI-SFDC_CONTACT';

delete
 from STAGE_CDI.BATCH_PARAMETER
where PROCESS_NAME = 'p_SFDC-CDI-SFDC_ADVISER_RI_CONTACT_STG';

delete
 from STAGE_CDI.BATCH_PARAMETER
where PROCESS_NAME = 'p_CDI-SFDC-PRU_HERITAGEARNASSOCIATION__C';

delete
 from STAGE_CDI.BATCH_PARAMETER
where PROCESS_NAME = 'p_SFDC-CDI-SFDC_ADVISER_HERITAGE_ARN_STG';

delete
 from STAGE_CDI.BATCH_PARAMETER
where PROCESS_NAME = 'p_CDI-SFDC-PRU_ACCOUNTTOACCOUNTRELATIONSHIP__C';

insert STAGE_CDI.BATCH_PARAMETER
(
    PROCESS_NAME,
    PARAMETER_NAME,
    PARAMETER_VALUE_DT,
    LASTMODIFIEDDT,
    LASTMODIFIEDBY
) 
values 
(
    'p_CDI-SFDC-ACCOUNT-ADVISER_NETWORK',
    'prm_EXTRACTDT',
    (select PARAMETER_VALUE from STAGE_CDI.ETL_JOB_CONTROL where PARAMETER_NAME = '$prm_Adv_Network_StgUpdateTime_sf'),
    CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'GMT Standard Time' AS datetime),
    'Script - INSERT_BATCH_PARAMETER_ASQLDB_DELTA_DPDB'
);

insert STAGE_CDI.BATCH_PARAMETER
(
    PROCESS_NAME,
    PARAMETER_NAME,
    PARAMETER_VALUE_DT,
    LASTMODIFIEDDT,
    LASTMODIFIEDBY
) 
values 
(
    'p_CDI-SFDC-ACCOUNT-ADVISER_FIRM',
    'prm_EXTRACTDT',
    (select PARAMETER_VALUE from STAGE_CDI.ETL_JOB_CONTROL where PARAMETER_NAME = '$prm_Adv_Firm_LastRunTime_sf'),
    CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'GMT Standard Time' AS datetime),
    'Script - INSERT_BATCH_PARAMETER_ASQLDB_DELTA_DPDB'
);

insert STAGE_CDI.BATCH_PARAMETER
(
    PROCESS_NAME,
    PARAMETER_NAME,
    PARAMETER_VALUE_DT,
    LASTMODIFIEDDT,
    LASTMODIFIEDBY
) 
values 
(
    'p_SFDC-CDI-SFDC_ADVISER_ACCOUNT_STG',
    'prm_EXTRACTDT',
    (select PARAMETER_VALUE from STAGE_CDI.ETL_JOB_CONTROL where PARAMETER_NAME = '$prm_Adv_Account_LastRunTime_stg'),
    CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'GMT Standard Time' AS datetime),
    'Script - INSERT_BATCH_PARAMETER_ASQLDB_DELTA_DPDB'
);

insert STAGE_CDI.BATCH_PARAMETER
(
    PROCESS_NAME,
    PARAMETER_NAME,
    PARAMETER_VALUE_DT,
    LASTMODIFIEDDT,
    LASTMODIFIEDBY
) 
values 
(
    'p_CDI-SFDC-ACCOUNT-ADVISER_OFFICE',
    'prm_EXTRACTDT',
    (select PARAMETER_VALUE from STAGE_CDI.ETL_JOB_CONTROL where PARAMETER_NAME = '$prm_Adv_Office_LastRunTime_sf'),
    CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'GMT Standard Time' AS datetime),
    'Script - INSERT_BATCH_PARAMETER_ASQLDB_DELTA_DPDB'
);

insert STAGE_CDI.BATCH_PARAMETER
(
    PROCESS_NAME,
    PARAMETER_NAME,
    PARAMETER_VALUE_DT,
    LASTMODIFIEDDT,
    LASTMODIFIEDBY
) 
values 
(
    'p_CDI-SFDC_CONTACT',
    'prm_EXTRACTDT',
    (select PARAMETER_VALUE from STAGE_CDI.ETL_JOB_CONTROL where PARAMETER_NAME = '$prm_Adv_RI_LastRunTime_sf'),
    CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'GMT Standard Time' AS datetime),
    'Script - INSERT_BATCH_PARAMETER_ASQLDB_DELTA_DPDB'
);

insert STAGE_CDI.BATCH_PARAMETER
(
    PROCESS_NAME,
    PARAMETER_NAME,
    PARAMETER_VALUE_DT,
    LASTMODIFIEDDT,
    LASTMODIFIEDBY
) 
values 
(
    'p_SFDC-CDI-SFDC_ADVISER_RI_CONTACT_STG',
    'prm_EXTRACTDT',
    (select PARAMETER_VALUE from STAGE_CDI.ETL_JOB_CONTROL where PARAMETER_NAME = '$prm_Adv_RI_Contact_LastRunTime_stg'),
    CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'GMT Standard Time' AS datetime),
    'Script - INSERT_BATCH_PARAMETER_ASQLDB_DELTA_DPDB'
);

insert STAGE_CDI.BATCH_PARAMETER
(
    PROCESS_NAME,
    PARAMETER_NAME,
    PARAMETER_VALUE_DT,
    LASTMODIFIEDDT,
    LASTMODIFIEDBY
) 
values 
(
    'p_CDI-SFDC-PRU_HERITAGEARNASSOCIATION__C',
    'prm_EXTRACTDT',
    (select PARAMETER_VALUE from STAGE_CDI.ETL_JOB_CONTROL where PARAMETER_NAME = '$prm_Adv_HeritageARN_ASSOCIATE_StgUpdateTime_sf'),
    CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'GMT Standard Time' AS datetime),
    'Script - INSERT_BATCH_PARAMETER_ASQLDB_DELTA_DPDB'
);

insert STAGE_CDI.BATCH_PARAMETER
(
    PROCESS_NAME,
    PARAMETER_NAME,
    PARAMETER_VALUE_DT,
    LASTMODIFIEDDT,
    LASTMODIFIEDBY
) 
values 
(
    'p_SFDC-CDI-SFDC_ADVISER_HERITAGE_ARN_STG',
    'prm_EXTRACTDT',
    (select PARAMETER_VALUE from STAGE_CDI.ETL_JOB_CONTROL where PARAMETER_NAME = '$prm_Adv_HRTG_ARN_StgUpdateTime_stg'),
    CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'GMT Standard Time' AS datetime),
    'Script - INSERT_BATCH_PARAMETER_ASQLDB_DELTA_DPDB'
);

insert STAGE_CDI.BATCH_PARAMETER
(
    PROCESS_NAME,
    PARAMETER_NAME,
    PARAMETER_VALUE_DT,
    LASTMODIFIEDDT,
    LASTMODIFIEDBY
) 
values 
(
    'p_CDI-SFDC-PRU_ACCOUNTTOACCOUNTRELATIONSHIP__C',
    'prm_EXTRACTDT',
    (select PARAMETER_VALUE from STAGE_CDI.ETL_JOB_CONTROL where PARAMETER_NAME = '$prm_Adv_ACCOUNT_REL_StgUpdateTime_sf'),
    CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'GMT Standard Time' AS datetime),
    'Script - INSERT_BATCH_PARAMETER_ASQLDB_DELTA_DPDB'
);
